---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 2.6.3
before_install: gem install bundler -v 1.17.2

# Run the test suites
script:
  - bundle exec rake                    # Backend specs

# Pipe the coverage data to Code Climate
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json